name: chdata
description: CH DATA
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  flex_color_scheme: ^7.3.1
  photo_view: ^0.15.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/zones/

flutter_intl:
  enabled: true
