name: gh-pages-external

on:
  push:
    branches: [ main, gh-pages-external ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.21.0
        with:
          cache: falss
          channel: stable

      - name: Restore packages
        run: flutter pub get

      - name: Generate Localizations
        run: flutter gen-l10n

      - name: Creates web build
        run: flutter build web --release --no-wasm-dry-run

      - name: Replace base href
        run: sed -i 's\<base href="/">\<base href="./">\g' build/web/index.html

      - name: Commit and push
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          JIT_OWNER: ${{ secrets.JIT_OWNER }}
          JIT_REPO: ${{ secrets.JIT_REPO }}
        run: |
          git clone https://$API_TOKEN_GITHUB@github.com/$JIT_OWNER/$JIT_REPO.git
          cd $JIT_REPO
          rm -rf *
          mv ../build/web/* .
          git config --global user.email "update[bot]@bots.noreply.github.com"
          git config --global user.name "update[bot]"
          git add .
          git commit -am update || echo "no changes"
          git push
